// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbGaLqaDb_9XUVemuV_8a2-o-4se2TSB0',
    appId: '1:723087504794:web:bd2283da59800d138af623',
    messagingSenderId: '723087504794',
    projectId: 'store-app-8537c',
    authDomain: 'store-app-8537c.firebaseapp.com',
    storageBucket: 'store-app-8537c.appspot.com',
    measurementId: 'G-VV9DJLTJNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv_MUyCNfoJrEhHiGIb-lSE3XuTK-vaqU',
    appId: '1:723087504794:android:356a3ae2777b68a58af623',
    messagingSenderId: '723087504794',
    projectId: 'store-app-8537c',
    storageBucket: 'store-app-8537c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39fmrMIrn-Y15IfdIEk5Mi57Mt_laAPE',
    appId: '1:723087504794:ios:6f4bea2cf26428988af623',
    messagingSenderId: '723087504794',
    projectId: 'store-app-8537c',
    storageBucket: 'store-app-8537c.appspot.com',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB39fmrMIrn-Y15IfdIEk5Mi57Mt_laAPE',
    appId: '1:723087504794:ios:9aa4d225a90d19288af623',
    messagingSenderId: '723087504794',
    projectId: 'store-app-8537c',
    storageBucket: 'store-app-8537c.appspot.com',
    iosBundleId: 'com.example.storeapp.RunnerTests',
  );
}
